#!/bin/bash
# This hook is sourced after this virtualenv is activated.
# SECURITY WARNING: keep the secret key used in production secret!
export DJANGO_SECRET_KEY
export NEVERCACHE_KEY
#export DJANGO_SETTINGS_MODULE
export DATABASE_NAME
export DATABASE_USER
export DATABASE_PASSWORD
export ADMIN_PASS
export DATABASE_URL
export SSH_USER
